-- Denied ids -- discovery entries reviewed and judged NOT crowd control. Split out on purpose:
-- this list only grows (every DoT/debuff you ever get hit by lands here once denied) and you never
-- need to read it, so it stays out of the data files you actually edit. addon.Discover skips these
-- forever and Discovery.lua's load-prune drops them from the ledger. Grown at sync: a reviewed id
-- that isn't CC gets `[spellID] = true` here (see the SYNC notes in Data.lua).
--
-- Must load before Discovery.lua (it captures addon.Denied at file scope) -- see cfDurations.toc.

local _, addon = ...

addon.Denied = {
    [133]  = true,  -- Fireball (no slow; the auto-SLOW was a coincident-snare false positive)
    [143]  = true,  -- Fireball (periodic damage)
    [589]  = true,  -- Shadow Word: Pain (DoT)
    [594]  = true,  -- Shadow Word: Pain (DoT)
    [348]  = true,  -- Immolate (fire DoT)
    [772]  = true,  -- Rend (bleed DoT)
    [6016] = true,  -- Pierce Armor (armor -50%)
    [6788] = true,  -- Weakened Soul (shield-immunity lockout)
    [6343] = true,  -- Thunder Clap (-10% melee attack speed only, no movement slow)
    [744]   = true, -- Poison (pure Nature DoT; auto-SLOW was a coincident-drop false positive)
    [3436]  = true, -- Wandering Plague (disease debuff)
    [3429]  = true, -- Plague Mind (mana-drain disease)
    [11196] = true, -- Recently Bandaged (first-aid lockout)
    [7102]  = true, -- Contagion of Rot (attack/cast-speed slow, not movement)
    [8927]  = true, -- Moonfire (Arcane DoT)
    [20300] = true, -- Judgement of the Crusader (holy-damage-taken debuff)
    [21183] = true, -- Judgement of the Crusader (other rank)
    [3105]  = true, -- Curse of Stalvan (-5 all attributes)
    [17390] = true, -- Faerie Fire (Feral) (armor reduction / anti-stealth)
    [6546]  = true, -- Rend (bleed DoT, creature rank)
    [7386]  = true, -- Sunder Armor (armor reduction)

    -- Synced 2026-06-21 -- DoTs / direct damage (not CC)
    [8925]  = true, -- Moonfire (Arcane DoT)
    [11918] = true, -- Poison (creature Nature DoT)
    [970]   = true, -- Shadow Word: Pain (DoT)
    [6751]  = true, -- Weak Poison (DoT)
    [409552] = true, -- Explosive Shot (SoD Hunter DoT)
    [3140]  = true, -- Fireball (damage + DoT)
    [145]   = true, -- Fireball (creature damage)
    [1978]  = true, -- Serpent Sting (DoT)
    [13549] = true, -- Serpent Sting (DoT)
    [13550] = true, -- Serpent Sting (DoT)
    [6222]  = true, -- Corruption (Shadow DoT)
    [13797] = true, -- Immolation Trap Effect (fire DoT)
    [11977] = true, -- Rend (bleed DoT)
    [6547]  = true, -- Rend (bleed DoT)
    [703]   = true, -- Garrote (bleed DoT)
    [1943]  = true, -- Rupture (bleed DoT)
    [6306]  = true, -- Acid Splash (creature AoE DoT)
    [6917]  = true, -- Venom Spit (creature damage + poison DoT)
    [400613] = true, -- Living Bomb (SoD Mage fire DoT)

    -- Synced 2026-06-21 -- stat / armor / attack-power / hit-chance debuffs (not CC)
    [6685]  = true, -- Piercing Shot (armor -)
    [1160]  = true, -- Demoralizing Shout (attack power -)
    [13730] = true, -- Demoralizing Shout (attack power -)
    [11971] = true, -- Sunder Armor (armor -)
    [6950]  = true, -- Faerie Fire (armor - / anti-stealth)
    [12166] = true, -- Muscle Tear (Strength -)
    [5884]  = true, -- Banshee Curse (hit chance -)
    [7272]  = true, -- Dust Cloud (hit chance -)
    [24423] = true, -- Screech (attack power -)
    [3427]  = true, -- Infected Wound (disease; physical damage taken +)
    [3584]  = true, -- Volatile Infection (disease; reflects Nature damage to allies)
    [7098]  = true, -- Curse of Mending (proc-heal debuff)

    -- Synced 2026-06-21 -- attack/cast-speed slow only (NOT movement)
    [8198]  = true, -- Thunder Clap (-10% melee attack speed only)
    [7103]  = true, -- Contagion of Rot (attack/cast-speed slow, not movement)

    -- Synced 2026-06-21 -- taunts / tracking / tame channels / misc (not CC)
    [355]   = true, -- Taunt (forced-attack, not loss of control)
    [694]   = true, -- Mocking Blow (taunt)
    [14323] = true, -- Hunter's Mark (tracking / ranged AP)
    [1130]  = true, -- Hunter's Mark (tracking / ranged AP)
    [19681] = true, -- Tame Dire Mottled Boar (tame channel)
    [19682] = true, -- Tame Surf Crawler (tame channel)
    [19683] = true, -- Tame Armored Scorpid (tame channel)
    [19696] = true, -- Tame Surf Crawler (tame channel)
    [19697] = true, -- Tame Armored Scorpid (tame channel)
    [19694] = true, -- Tame Dire Mottled Boar (tame channel)
    [1515]  = true, -- Tame Beast (tame channel)
    [403501] = true, -- Haunt (SoD Warlock damage-amp buff)
    [5810]  = true, -- Stone Skin (creature SELF-buff; the slow is on the caster, not you)

    -- Synced 2026-06-22 -- DoTs / damage (not CC)
    [7367]  = true, -- Infected Bite (Nature DoT + damage-taken debuff)
    [16400] = true, -- Poison (Nature DoT)
    -- Synced 2026-06-22 -- stat / armor / attack-power debuffs (not CC)
    [8282]  = true, -- Curse of Blood (+physical damage taken)
    [8016]  = true, -- Spirit Decay (-Spirit)
    [6205]  = true, -- Curse of Weakness (-damage done)
    [6190]  = true, -- Demoralizing Shout (-attack power, creature)
    [99]    = true, -- Demoralizing Roar (-attack power, druid bear)
    [7405]  = true, -- Sunder Armor (-armor)
    [3150]  = true, -- Rabies (disease; -health regen / -stats)
    -- Synced 2026-06-22 -- not-a-movement-slow / taunts / fleeing
    [3358]  = true, -- Leech Poison (leech DoT; auto-SLOW was a false positive, no movement effect)
    [20184] = true, -- Judgement of Justice (prevents fleeing; NOT a movement slow)
    [21008] = true, -- Mocking Blow (taunt)
    [1161]  = true, -- Challenging Shout (AoE taunt)
    [12721] = true, -- Deep Wound (Warrior Deep Wounds bleed DoT)

    -- Synced 2026-06-22 (batch 2)
    [13551] = true, -- Serpent Sting (Hunter DoT)
    [14298] = true, -- Immolation Trap Effect (Hunter fire DoT)
    [25771] = true, -- Forbearance (Paladin lockout after Divine Shield/BoP/LoH)
    [4507]  = true, -- Target Dummy Spawn Effect (taunt)
    [8733]  = true, -- Blessing of Blackfathom (beneficial buff, not a debuff)
    [3439]  = true, -- Wandering Plague (disease debuff; auto-SLOW was a false positive, sibling of 3436)

    -- Synced 2026-06-22 (batch 3)
    [18199] = true, -- Fireball (damage + DoT)
    [15263] = true, -- Holy Fire (Holy damage + DoT)
    [992]   = true, -- Shadow Word: Pain (DoT)
    [6223]  = true, -- Corruption (Shadow DoT, creature rank)
    [12097] = true, -- Pierce Armor (-armor)
    [3147]  = true, -- Rend Flesh (bleed DoT; auto-SLOW false positive)
    [10651] = true, -- Curse of the Eye (-damage done / -cast speed, NOT movement)
    [10653] = true, -- Curse of the Eye (same; different caster/id)

    -- Synced 2026-06-23 -- DoTs / dummy auras (not CC)
    [6946]  = true, -- Curse of the Bleakheart (dummy aura, no mechanic; Bleakheart Trickster)
    [1079]  = true, -- Rip (Druid bleed DoT finisher; your own spell)
    -- Synced 2026-06-23 -- stat / healing debuffs (not CC)
    [7068]  = true, -- Veil of Shadow (-75% healing taken; auto-SLOW false positive, not movement)
    [6816]  = true, -- Corrupted Strength (-Strength; auto-SLOW false positive)
    [6817]  = true, -- Corrupted Agility (-Agility)
    [6818]  = true, -- Corrupted Intellect (-Intellect)
    [6819]  = true, -- Corrupted Stamina (-Stamina)
    [18545] = true, -- Scorpid Sting (-1 Strength/Agility stat debuff, not CC)

    -- Synced 2026-06-23 (batch 2) -- Gnomeregan + PvP: DoTs / damage / stat debuffs / taunts (not CC)
    [16511] = true, -- Hemorrhage (+physical damage taken debuff)
    [1735]  = true, -- Demoralizing Roar (-50 melee attack power)
    [9490]  = true, -- Demoralizing Roar (-65 melee attack power; auto-SLOW false positive)
    [8401]  = true, -- Fireball (fire damage + DoT)
    [2818]  = true, -- Deadly Poison (Nature DoT)
    [9775]  = true, -- Irradiated (disease Nature DoT, also hits nearby party)
    [9459]  = true, -- Corrosive Ooze (-physical damage dealt)
    [6795]  = true, -- Growl (taunt)

    -- Synced 2026-06-28 -- DoTs / direct damage (not CC)
    [11790] = true, -- Poison Cloud (creature Nature AoE DoT)
    [8928]  = true, -- Moonfire (Druid Arcane DoT, Rank 6)
    [13812] = true, -- Explosive Trap Effect (Hunter AoE fire DoT)
    [7947]  = true, -- Localized Toxin (creature Nature DoT)
    [8806]  = true, -- Poisoned Shot (creature weapon dmg + Nature DoT)
    [9658]  = true, -- Flame Buffet (creature fire dmg + fire-damage-taken debuff)
    [10447] = true, -- Flame Shock (Shaman fire dmg + DoT, Rank 4)
    [6217]  = true, -- Curse of Agony (Warlock Shadow DoT; auto-SLOW false positive)
    [6548]  = true, -- Rend (Warrior bleed DoT)
    [5416]  = true, -- Venom Sting (creature dmg + Nature DoT)
    [2819]  = true, -- Deadly Poison II (Rogue Nature DoT)
    [709]   = true, -- Drain Life (Warlock health-leech channel)
    [8313]  = true, -- Poison (creature Nature DoT)
    [18265] = true, -- Siphon Life (creature health-leech DoT)
    [13443] = true, -- Rend (creature bleed DoT)
    [19277] = true, -- Devouring Plague (disease DoT)
    [8633]  = true, -- Garrote (Rogue bleed DoT; does NOT silence in vanilla)
    [7648]  = true, -- Corruption (Warlock Shadow DoT, Rank 4)
    [2941]  = true, -- Immolate (Warlock fire dmg + DoT, Rank 4)
    [13552] = true, -- Serpent Sting (Hunter Nature DoT, Rank 5)
    [2767]  = true, -- Shadow Word: Pain (Priest Shadow DoT, Rank 5)
    [13884] = true, -- Withering Poison (creature Nature DoT + Str/Agi reduction)

    -- Synced 2026-06-28 -- stat / armor / attack-power / damage-taken debuffs (not CC)
    [12579] = true, -- Winter's Chill (Mage +Frost-spell-crit-taken; NOT a movement slow despite the name)
    [15258] = true, -- Shadow Vulnerability (+Shadow damage taken)
    [20185] = true, -- Judgement of Light (heal-on-attack proc debuff)
    [8649]  = true, -- Expose Armor (Rogue armor reduction)
    [13444] = true, -- Sunder Armor (creature armor reduction)
    [8380]  = true, -- Sunder Armor (armor reduction / threat)
    [770]   = true, -- Faerie Fire (armor reduction / anti-stealth; non-feral)
    [16231] = true, -- Curse of Recklessness (+AP / -armor, grants fear-immunity; anti-CC, not CC)
    [24577] = true, -- Screech (creature -attack power; NOT attack-speed and NOT movement)
    [6951]  = true, -- Decayed Strength (disease -Strength)
    [8014]  = true, -- Tetanus (disease -Stamina)
    [15286] = true, -- Vampiric Embrace (Priest healing buff, not a debuff)
    [8192]  = true, -- Mind Soothe (reduces aggro/detection range only; not Pacify or Silence)

    -- Synced 2026-06-28 -- false-positive auto-SLOW (no movement effect)
    [17775] = true, -- Air Bubbles (underwater-breathing aura; auto-SLOW was a false positive)

    -- Synced 2026-07-02 -- DoTs / stat & healing debuffs / utility (not CC)
    [1543]  = true, -- Flare (Hunter utility; reveals stealth in an area, no target aura/CC)
    [3396]  = true, -- Corrosive Poison (Nature DoT + armor -60; Giant Moss Creeper 2349)
    [6278]  = true, -- Creeping Mold (Nature disease DoT; Mirefin Muckdweller 4361)
    [8257]  = true, -- Venom Sting (Nature DoT; Vile Sting 5937)
    [8632]  = true, -- Garrote (creature bleed DoT; does NOT silence in vanilla; cf. 8633)
    [11554] = true, -- Demoralizing Shout (creature -melee attack power; NOT movement)
    [12294] = true, -- Mortal Strike (creature; weapon damage + -50% healing debuff)
    [15264] = true, -- Holy Fire (Holy direct damage + DoT)
    [18159] = true, -- Curse of the Fallen Magram (+15% damage taken debuff; not CC)
    -- Synced 2026-07-02 -- false-positive auto-SLOW (no movement effect)
    [18172] = true, -- Kodo Kombobulator (dummy quest aura; auto-SLOW was a speed-buff-fade false positive)

    -- Synced 2026-07-04 -- DoTs / direct damage (not CC)
    [172]    = true, -- Corruption (Warlock Shadow DoT)
    [980]    = true, -- Curse of Agony (Warlock Shadow DoT)
    [11711]  = true, -- Curse of Agony (Warlock Shadow DoT)
    [18266]  = true, -- Curse of Agony (creature Shadow DoT; auto-SLOW false positive; Searing Blade Cultist 11322)
    [1822]   = true, -- Rake (Druid bleed DoT)
    [1823]   = true, -- Rake (Druid bleed DoT)
    [9007]   = true, -- Pounce Bleed (Druid bleed DoT; the Pounce STUN 9005/9823/9827 is a separate id)
    [9493]   = true, -- Rip (Druid bleed DoT)
    [8639]   = true, -- Rupture (Rogue bleed DoT)
    [8640]   = true, -- Rupture (Rogue bleed DoT)
    [8050]   = true, -- Flame Shock (Shaman fire DoT)
    [8052]   = true, -- Flame Shock (Shaman fire DoT)
    [8053]   = true, -- Flame Shock (creature fire DoT; Kurzen Subchief 978)
    [14914]  = true, -- Holy Fire (Priest Holy dmg + DoT)
    [8402]   = true, -- Fireball (Mage fire dmg + DoT)
    [400573] = true, -- Arcane Blast (Mage nuke + self damage-buff, SoD)
    [18197]  = true, -- Poison (Nature DoT)
    [3583]   = true, -- Deadly Poison (creature Nature DoT; Darkmist Recluse 4378)
    [434312] = true, -- Deadly Poison (Rogue Nature DoT)
    [8929]   = true, -- Moonfire (Druid Arcane DoT)
    [15798]  = true, -- Moonfire (creature Arcane DoT; Tyranis Malem 5643)
    [11665]  = true, -- Immolate (Warlock fire dmg + DoT)
    [7651]   = true, -- Drain Life (Warlock health-leech DoT)
    [8289]   = true, -- Drain Soul (Warlock channel DoT)
    [402668] = true, -- Vampiric Touch (Priest Shadow DoT, SoD)
    [413259] = true, -- Mind Sear (Priest Shadow channel DoT, SoD)
    [431655] = true, -- Mind Spike (Priest frost+shadow nuke, SoD)
    [431688] = true, -- Void Zone (Priest Shadow ground AoE, SoD)
    [425204] = true, -- Void Plague (Priest Shadow disease DoT, SoD)
    [411995] = true, -- Shadow Crash (Shadow DoT, SoD)
    [411956] = true, -- Curse of Blackfathom (creature Shadow DoT; Gelihast 204921)
    [427717] = true, -- Unstable Affliction (Warlock Shadow DoT, SoD; does NOT silence in Classic)
    [1228049] = true, -- Shadowflame (Fire+Shadow DoT)
    [405953] = true, -- Torrential Downpour (Druid nature/frost DoT, SoD)
    [414900] = true, -- Corrupted Molten Fury Totem (totem fire DoT, SoD)
    [427625] = true, -- Corrosion (creature Nature DoT; Aku'mai 213334)
    [412096] = true, -- Crimson Tempest (Rogue AoE bleed, SoD)
    [412609] = true, -- Deep Wound (Warrior bleed DoT)
    [424785] = true, -- Saber Slash (Rogue strike + bleed, SoD)
    [407794] = true, -- Triple Puncture (creature bleed DoT; Blackfathom Elite 204091)
    [430723] = true, -- Triple Puncture (creature bleed DoT; auto-SLOW false positive; Blackfathom Elite 204645)
    [412072] = true, -- Shadow Strike (creature shadow dmg + vuln debuff; Gelihast rank 1)
    [412079] = true, -- Shadow Strike (creature shadow dmg + vuln debuff; Gelihast rank 2)
    [412080] = true, -- Shadow Strike (creature shadow dmg + vuln debuff; Gelihast rank 3)
    [404806] = true, -- Depth Charge (creature periodic-trigger damage; Fathom Elemental 202838)
    [407767] = true, -- Forked Lightning (Shaman damage, SoD)

    -- Synced 2026-07-04 -- stat / armor / attack-power / hit / resistance / vulnerability debuffs (not CC)
    [3148]   = true, -- Head Crack (-1 Stamina stat debuff; NOT a stun despite the name)
    [9791]   = true, -- Head Crack (-1 Stamina stat debuff; NOT a stun)
    [3237]   = true, -- Curse of Thule (-2 Spirit)
    [4974]   = true, -- Wither Touch (-Stamina/-Spirit curse)
    [6530]   = true, -- Sling Dirt (-40% hit chance)
    [7646]   = true, -- Curse of Weakness (creature -damage dealt; Witherbark Shadow Hunter 2557)
    [18267]  = true, -- Curse of Weakness (creature -damage done; Jergosh the Invoker 11518)
    [11555]  = true, -- Demoralizing Shout (-attack power)
    [402811] = true, -- Demoralize (-attack power, SoD)
    [17963]  = true, -- Sundering Cleave (-armor, stacking)
    [18070]  = true, -- Earthborer Acid (-armor / -resistance, stacking)
    [407095] = true, -- Crunch Armor (creature -physical resistance; Ghamoo-ra 201722)
    [407993] = true, -- Mangle (+bleed-damage-taken amplifier, SoD)
    [428482] = true, -- Shadow Seep (-max health / +shadow damage taken; Aku'mai 213334)

    -- Synced 2026-07-04 -- attack/cast-speed slow only (NOT movement)
    [402808] = true, -- Cripple (-10% melee attack speed, SoD; not movement despite the name)
    [461829] = true, -- Thunder Clap (-10% melee attack speed; not a movement slow)

    -- Synced 2026-07-04 -- self-buffs / protection / beneficial / interrupt+taunt / cosmetic (not CC)
    [8041]   = true, -- Serpent Form (creature self-shapeshift buff; self-silence, not enemy CC)
    [8326]   = true, -- Ghost (dead-player ghost self-buff; +speed on self)
    [23230]  = true, -- Blood Fury (Orc racial self-buff; the debuff is the healing-reduction on self)
    [405688] = true, -- Riptide Bubbles (beneficial speed/mana INCREASE buff, SoD)
    [429541] = true, -- Dark Protection (99% damage-reduction protection buff; Aku'mai 213334)
    [432275] = true, -- Carnage (+16% damage self-buff, SoD)
    [1218358] = true, -- Rabid Frenzy (creature enrage self-buff; Theomis 3619)
    [431060] = true, -- Flight Insurance (immunity + haste beneficial buff)
    [424190] = true, -- Unbalanced Idol (Druid idol item proc buff)
    [408681] = true, -- Earth Shock (nature dmg + interrupt + taunt, SoD; not CC)
    [408683] = true, -- Earth Shock (nature dmg + interrupt + taunt, SoD; not CC)
    [408685] = true, -- Earth Shock (nature dmg + interrupt + taunt, SoD; not CC)
    [408687] = true, -- Earth Shock (nature dmg + interrupt + taunt, SoD; not CC)
    [405092] = true, -- Underwater Pressure (breathing-reduction; environmental, SoD)
    [423135] = true, -- Sleep (cosmetic dream-phase: mod-size/screen/phase, no incapacitate aura; SoD)
    [402686] = true, -- Wild Polymorph (cosmetic melon-transform: Dummy + Mod Size, no Confuse aura; SoD critter prop)

    -- Synced 2026-07-04 (batch 2) -- contributor export: DoTs / stat & healing debuffs / quest / taunts / self-buffs (not CC)
    [2943]   = true, -- Touch of Weakness (Priest reactive curse; -physical damage done + shadow proc)
    [19276]  = true, -- Devouring Plague (Priest disease DoT; sibling rank of denied 19277)
    [414684] = true, -- Sunfire (SoD Druid Nature nuke + DoT)
    [437132] = true, -- Dreamstate (SoD Druid damage-taken modifier buff; not CC)
    [461966] = true, -- Vampiric Embrace (Priest self healing buff, SoD; cf. denied 15286)
    [11983]  = true, -- Steam Jet (creature -30% hit chance + minor AoE dmg; Boiling Elemental 10757; not movement)
    [6714]   = true, -- Test of Faith (Thousand Needles quest 1149 teleport-event root; scripted, not combat CC)
    [6716]   = true, -- Test of Faith (quest 1149 periodic trigger aura; Dorn Plainstalker 2986; not CC)
    [6873]   = true, -- Foul Chill (+50 Frost damage taken vulnerability; Befouled Water Elemental 3917; not a snare despite the name)
    [6922]   = true, -- Curse of the Shadowhorn (damage-done/-taken stat curse; not CC)
    [15007]  = true, -- Resurrection Sickness (death-penalty stat debuff; not CC)
    [409372] = true, -- Growl (SoD taunt variant; forced-attack, not CC; cf. denied creature Growl 6795)
    [433804] = true, -- Blood for the Blood Loa (SoD self-cast dummy aura; not CC)
    [435205] = true, -- Pyromantic Mishap (SoD Mage-rune absorb/immunity mechanic; Scorched Screeching Roguefeather 217669; not CC)
}
