-- Denied ids -- discovery entries reviewed and judged NOT crowd control. Split out on purpose:
-- this list only grows (every DoT/debuff you ever get hit by lands here once denied) and you never
-- need to read it, so it stays out of the data files you actually edit. addon.Discover skips these
-- forever and Discovery.lua's load-prune drops them from the ledger. Grown at sync: a reviewed id
-- that isn't CC gets `[spellID] = true` here (see the SYNC notes in Data.lua).
--
-- Must load before Discovery.lua (it captures addon.Denied at file scope) -- see cfDurations.toc.

local _, addon = ...

addon.Denied = {
    [133]  = true,  -- Fireball (no slow; the auto-SLOW was a coincident-snare false positive)
    [143]  = true,  -- Fireball (periodic damage)
    [589]  = true,  -- Shadow Word: Pain (DoT)
    [594]  = true,  -- Shadow Word: Pain (DoT)
    [348]  = true,  -- Immolate (fire DoT)
    [772]  = true,  -- Rend (bleed DoT)
    [6016] = true,  -- Pierce Armor (armor -50%)
    [6788] = true,  -- Weakened Soul (shield-immunity lockout)
    [6343] = true,  -- Thunder Clap (-10% melee attack speed only, no movement slow)
    [744]   = true, -- Poison (pure Nature DoT; auto-SLOW was a coincident-drop false positive)
    [3436]  = true, -- Wandering Plague (disease debuff)
    [3429]  = true, -- Plague Mind (mana-drain disease)
    [11196] = true, -- Recently Bandaged (first-aid lockout)
    [7102]  = true, -- Contagion of Rot (attack/cast-speed slow, not movement)
    [8927]  = true, -- Moonfire (Arcane DoT)
    [20300] = true, -- Judgement of the Crusader (holy-damage-taken debuff)
    [21183] = true, -- Judgement of the Crusader (other rank)
    [3105]  = true, -- Curse of Stalvan (-5 all attributes)
    [17390] = true, -- Faerie Fire (Feral) (armor reduction / anti-stealth)
    [6546]  = true, -- Rend (bleed DoT, creature rank)
    [7386]  = true, -- Sunder Armor (armor reduction)

    -- Synced 2026-06-21 -- DoTs / direct damage (not CC)
    [8925]  = true, -- Moonfire (Arcane DoT)
    [11918] = true, -- Poison (creature Nature DoT)
    [970]   = true, -- Shadow Word: Pain (DoT)
    [6751]  = true, -- Weak Poison (DoT)
    [409552] = true, -- Explosive Shot (SoD Hunter DoT)
    [3140]  = true, -- Fireball (damage + DoT)
    [145]   = true, -- Fireball (creature damage)
    [1978]  = true, -- Serpent Sting (DoT)
    [13549] = true, -- Serpent Sting (DoT)
    [13550] = true, -- Serpent Sting (DoT)
    [6222]  = true, -- Corruption (Shadow DoT)
    [13797] = true, -- Immolation Trap Effect (fire DoT)
    [11977] = true, -- Rend (bleed DoT)
    [6547]  = true, -- Rend (bleed DoT)
    [703]   = true, -- Garrote (bleed DoT)
    [1943]  = true, -- Rupture (bleed DoT)
    [6306]  = true, -- Acid Splash (creature AoE DoT)
    [6917]  = true, -- Venom Spit (creature damage + poison DoT)
    [400613] = true, -- Living Bomb (SoD Mage fire DoT)

    -- Synced 2026-06-21 -- stat / armor / attack-power / hit-chance debuffs (not CC)
    [6685]  = true, -- Piercing Shot (armor -)
    [1160]  = true, -- Demoralizing Shout (attack power -)
    [13730] = true, -- Demoralizing Shout (attack power -)
    [11971] = true, -- Sunder Armor (armor -)
    [6950]  = true, -- Faerie Fire (armor - / anti-stealth)
    [12166] = true, -- Muscle Tear (Strength -)
    [5884]  = true, -- Banshee Curse (hit chance -)
    [7272]  = true, -- Dust Cloud (hit chance -)
    [24423] = true, -- Screech (attack power -)
    [3427]  = true, -- Infected Wound (disease; physical damage taken +)
    [3584]  = true, -- Volatile Infection (disease; reflects Nature damage to allies)
    [7098]  = true, -- Curse of Mending (proc-heal debuff)

    -- Synced 2026-06-21 -- attack/cast-speed slow only (NOT movement)
    [8198]  = true, -- Thunder Clap (-10% melee attack speed only)
    [7103]  = true, -- Contagion of Rot (attack/cast-speed slow, not movement)

    -- Synced 2026-06-21 -- taunts / tracking / tame channels / misc (not CC)
    [355]   = true, -- Taunt (forced-attack, not loss of control)
    [694]   = true, -- Mocking Blow (taunt)
    [14323] = true, -- Hunter's Mark (tracking / ranged AP)
    [1130]  = true, -- Hunter's Mark (tracking / ranged AP)
    [19681] = true, -- Tame Dire Mottled Boar (tame channel)
    [19682] = true, -- Tame Surf Crawler (tame channel)
    [19683] = true, -- Tame Armored Scorpid (tame channel)
    [19696] = true, -- Tame Surf Crawler (tame channel)
    [19697] = true, -- Tame Armored Scorpid (tame channel)
    [19694] = true, -- Tame Dire Mottled Boar (tame channel)
    [1515]  = true, -- Tame Beast (tame channel)
    [403501] = true, -- Haunt (SoD Warlock damage-amp buff)
    [5810]  = true, -- Stone Skin (creature SELF-buff; the slow is on the caster, not you)

    -- Synced 2026-06-22 -- DoTs / damage (not CC)
    [7367]  = true, -- Infected Bite (Nature DoT + damage-taken debuff)
    [16400] = true, -- Poison (Nature DoT)
    -- Synced 2026-06-22 -- stat / armor / attack-power debuffs (not CC)
    [8282]  = true, -- Curse of Blood (+physical damage taken)
    [8016]  = true, -- Spirit Decay (-Spirit)
    [6205]  = true, -- Curse of Weakness (-damage done)
    [6190]  = true, -- Demoralizing Shout (-attack power, creature)
    [99]    = true, -- Demoralizing Roar (-attack power, druid bear)
    [7405]  = true, -- Sunder Armor (-armor)
    [3150]  = true, -- Rabies (disease; -health regen / -stats)
    -- Synced 2026-06-22 -- not-a-movement-slow / taunts / fleeing
    [3358]  = true, -- Leech Poison (leech DoT; auto-SLOW was a false positive, no movement effect)
    [20184] = true, -- Judgement of Justice (prevents fleeing; NOT a movement slow)
    [21008] = true, -- Mocking Blow (taunt)
    [1161]  = true, -- Challenging Shout (AoE taunt)
    [12721] = true, -- Deep Wound (Warrior Deep Wounds bleed DoT)

    -- Synced 2026-06-22 (batch 2)
    [13551] = true, -- Serpent Sting (Hunter DoT)
    [14298] = true, -- Immolation Trap Effect (Hunter fire DoT)
    [25771] = true, -- Forbearance (Paladin lockout after Divine Shield/BoP/LoH)
    [4507]  = true, -- Target Dummy Spawn Effect (taunt)
    [8733]  = true, -- Blessing of Blackfathom (beneficial buff, not a debuff)
    [3439]  = true, -- Wandering Plague (disease debuff; auto-SLOW was a false positive, sibling of 3436)

    -- Synced 2026-06-22 (batch 3)
    [18199] = true, -- Fireball (damage + DoT)
    [15263] = true, -- Holy Fire (Holy damage + DoT)
    [992]   = true, -- Shadow Word: Pain (DoT)
    [6223]  = true, -- Corruption (Shadow DoT, creature rank)
    [12097] = true, -- Pierce Armor (-armor)
    [3147]  = true, -- Rend Flesh (bleed DoT; auto-SLOW false positive)
    [10651] = true, -- Curse of the Eye (-damage done / -cast speed, NOT movement)
    [10653] = true, -- Curse of the Eye (same; different caster/id)
}
